"""add indexes to clicks table

Revision ID: d8acdc2d4c5e
Revises: be024f86a278
Create Date: 2026-04-21 16:10:53.710227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8acdc2d4c5e'
down_revision: Union[str, Sequence[str], None] = 'be024f86a278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clicks_clicked_at'), 'clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_clicks_url_id'), 'clicks', ['url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clicks_url_id'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_clicked_at'), table_name='clicks')
    op.drop_table('clicks')
    # ### end Alembic commands ###
